### PR TITLE
Add support for IE11

### PR DESCRIPTION
**Pull request by gabskoro**
Hi Guys, I'm using the library in one of my projects and I noticed it's failing on IE11 because the bundle is having arrow functions in the code which is not supported by IE11.

So here I'm using babel to bundle the code with "normal" functions. Let me know if you will need anything else from my side.

Thank you

### CODE REVIEW

**Comment by gabskoro** [comment]
Hi @bluebill1049 could you please take a look and let me know if this is fine :)

**Comment by bluebill1049** [comment]
hey, @gabskoro I am sorry I missed your PR! thanks for putting this together, however, start this year I stopped include IE 11 for all the libraries that I have open-sourced. if users want to support IE11, they will have to include their own polyfill. sorry about that, and again thanks for putting this together. ❤️

**Comment by gabskoro** [comment]
Hi @bluebill1049, thank you for your answer. I respect your decision, but unfortunately, template literals need to be transpiled, so polyfills won't fix anything here.

For the ones who will come across this issue, what I did to solve this problem was to transpile it on my own through my webpack config.

Steps:
1. Add `react-simple-animate`  as a dependency to your package.json file
2. As webpack will not compile anything from the `node_modules` folder, exclude everything in the `node_modules` except the `react-simple-animate` library
3. Import the `react-simple-animate` library in your application

**Comment by bluebill1049** [comment]
Thank you very much for your understanding + contribution + solution. 🙏

**Pull request closed without merging**
